using System;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Smudge.SourceGenerator;

internal static class Emitter
{
    internal static void Emit(SourceProductionContext ctx, ClassModel model)
    {
        foreach (var diagnostic in model.Diagnostics.Items)
            ctx.ReportDiagnostic(diagnostic.ToDiagnostic());

        if (!model.ShouldGenerate)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.Namespace is not null)
            sb.AppendLine($"namespace {model.Namespace};");
        
        var baseInterface = model.Mode switch
        {
            DirtyMode.Aggregated => "global::Smudge.ISmudgeable",
            DirtyMode.PerProperty => "global::Smudge.IPerPropertySmudgeable",
            _ => throw new ArgumentOutOfRangeException(nameof(model.Mode), model.Mode, null)
        };

        // No accessibility modifier: the user's declaration supplies it, so we
        // can't conflict with an `internal` class.
        sb.AppendLine($"partial class {model.Name} : {baseInterface}");
        sb.AppendLine("{");

        if (model.Mode == DirtyMode.Aggregated)
            EmitAggregatedMembers(sb);
        else
            EmitPerPropertyMembers(sb, model);

        var properties = model.Properties.Items;
        for (var i = 0; i < properties.Length; i++)
        {
            var markDirty = model.Mode == DirtyMode.Aggregated
                ? "_dirty = true;"
                : $"_dirtyBits |= 1UL << {i};";
            EmitProperty(sb, properties[i], markDirty);
        }

        sb.AppendLine("}");
        ctx.AddSource(model.HintName, sb.ToString());
    }
    
    private static void EmitAggregatedMembers(StringBuilder sb) =>
        sb.AppendLine("""
                          private bool _dirty;
                          public bool IsDirty => _dirty;
                          public void WipeClean() => _dirty = false;
                      """).AppendLine();
    
    private static void EmitPerPropertyMembers(StringBuilder sb, ClassModel model)
    {
        var properties = model.Properties.Items;

        var switchArms = new StringBuilder();
        var collectors = new StringBuilder();
        for (var i = 0; i < properties.Length; i++)
        {
            switchArms.AppendLine(
                $"""        "{properties[i].PropertyName}" => (_dirtyBits & (1UL << {i})) != 0UL,""");
            collectors.AppendLine(
                $"""            if ((_dirtyBits & (1UL << {i})) != 0UL) result.Add("{properties[i].PropertyName}");""");
        }

        sb.AppendLine($$"""
                            private ulong _dirtyBits;
                            public bool IsDirty => _dirtyBits != 0UL;
                            public void WipeClean() => _dirtyBits = 0UL;

                            public bool IsPropertyDirty(string propertyName) => propertyName switch
                            {
                        {{switchArms.ToString().TrimEnd()}}
                                _ => throw new global::System.ArgumentException("Invalid property name", nameof(propertyName)),
                            };

                            public global::System.Collections.Generic.IReadOnlyCollection<string> DirtyProperties
                            {
                                get
                                {
                                    var result = new global::System.Collections.Generic.List<string>();
                        {{collectors.ToString().TrimEnd()}}
                                    return result;
                                }
                            }
                        """);
        sb.AppendLine();
    }
    
    private static void EmitProperty(StringBuilder sb, PropertyModel p, string markDirty) =>
        sb.AppendLine($$"""
                            private {{p.TypeName}} {{p.FieldName}} = {{p.DefaultValue}};
                            {{p.Accessibility}} partial {{p.TypeName}} {{p.PropertyName}}
                            {
                                get => {{p.FieldName}};
                                set
                                {
                                    if (!global::System.Collections.Generic.EqualityComparer<{{p.TypeName}}>.Default.Equals({{p.FieldName}}, value))
                                    {
                                        {{p.FieldName}} = value;
                                        {{markDirty}}
                                    }
                                }
                            }
                        """).AppendLine();
}